// Prints the SQL for triggers, RLS policies, and grants. Run it and paste the output into
// the Supabase SQL editor:  node scripts/generateTriggersAndPolicies.js
//
// Access levels are read from the JWT's `app_metadata` claim, which only the service role
// can write (see supabase/functions/user-management/index.ts). `user_metadata` must NEVER be
// used for authorization: users can write their own via supabase.auth.updateUser({data}).

const modifiedAtTables = ['parent', 'deliverer', 'kid', 'order_record'];
const allTables = [...modifiedAtTables, 'order_parent', 'order_kid'];
const views = [
  'parent_view',
  'finished_order_view',
  'kid_view',
  'rostered_kid_view',
  'parent_options',
  'deliverer_options',
  'kid_order_view',
  'parent_order_view',
];

// Policy names this script has used over time. Every one gets dropped before the current
// set is created, so re-running never leaves a stale permissive policy behind. This matters:
// Postgres ORs permissive policies together, so one forgotten blanket policy would silently
// re-grant everything.
const obsoletePolicies = [
  'access_for_logged_in_users',
  'select_for_authenticated',
  'insert_for_writers',
  'update_for_writers',
  'delete_for_writers',
];

const helpers = `
-- Access level of the current request.
--
-- Reads the server-controlled app_metadata claim first, then falls back to looking the user
-- up in auth.users. The fallback matters twice over:
--   1. app_metadata is baked into a JWT when it is issued, so a token predating an access
--      level change would otherwise carry a stale value for up to jwt_expiry.
--   2. It returns NULL for an account that has no level assigned at all. That is the
--      important case: a self-registered account must get nothing, not a default.
--
-- SECURITY DEFINER so it can read auth.users; search_path is pinned and EXECUTE is revoked
-- from anon/public, so it cannot be repurposed.
CREATE OR REPLACE FUNCTION public.app_access_level()
RETURNS TEXT
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT COALESCE(
    NULLIF(auth.jwt() -> 'app_metadata' ->> 'access_level', ''),
    (SELECT NULLIF(u.raw_app_meta_data ->> 'access_level', '')
       FROM auth.users u WHERE u.id = auth.uid())
  );
$$;

CREATE OR REPLACE FUNCTION public.app_can_write()
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SET search_path = ''
AS $$
  SELECT public.app_access_level() IN ('readWrite', 'admin');
$$;

-- Any assigned level may read. NULL (no level assigned) may not.
CREATE OR REPLACE FUNCTION public.app_can_read()
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SET search_path = ''
AS $$
  SELECT public.app_access_level() IS NOT NULL;
$$;

REVOKE ALL ON FUNCTION public.app_access_level() FROM anon, public;
REVOKE ALL ON FUNCTION public.app_can_write() FROM anon, public;
REVOKE ALL ON FUNCTION public.app_can_read() FROM anon, public;
GRANT EXECUTE ON FUNCTION public.app_access_level() TO authenticated;
GRANT EXECUTE ON FUNCTION public.app_can_write() TO authenticated;
GRANT EXECUTE ON FUNCTION public.app_can_read() TO authenticated;
`;

const triggers = modifiedAtTables
  .map(
    (t) => `
DROP TRIGGER IF EXISTS update_${t}_modified_at ON ${t};
CREATE TRIGGER update_${t}_modified_at
BEFORE UPDATE ON ${t}
FOR EACH ROW
EXECUTE FUNCTION update_modified_at();`,
  )
  .join('\n');

const tablePolicies = allTables
  .map(
    (t) => `
ALTER TABLE ${t} ENABLE ROW LEVEL SECURITY;
${obsoletePolicies.map((p) => `DROP POLICY IF EXISTS ${p} ON ${t};`).join('\n')}

-- Anyone with an assigned access level may read. A self-registered account has none.
CREATE POLICY select_for_authenticated ON ${t}
FOR SELECT TO authenticated
USING (public.app_can_read());

-- Only readWrite/admin may change anything.
CREATE POLICY insert_for_writers ON ${t}
FOR INSERT TO authenticated
WITH CHECK (public.app_can_write());

CREATE POLICY update_for_writers ON ${t}
FOR UPDATE TO authenticated
USING (public.app_can_write())
WITH CHECK (public.app_can_write());

CREATE POLICY delete_for_writers ON ${t}
FOR DELETE TO authenticated
USING (public.app_can_write());

REVOKE ALL ON TABLE ${t} FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE ${t} TO authenticated;`,
  )
  .join('\n');

// create_order (dataModel.sql) is the transactional order snapshot. It is SECURITY INVOKER,
// so the table policies above still gate what it can write — this grant only makes it
// callable through PostgREST's /rpc endpoint.
const functionGrants = `
REVOKE ALL ON FUNCTION public.create_order(JSONB, JSONB, JSONB) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.create_order(JSONB, JSONB, JSONB) TO authenticated;`;

// Views are declared WITH (security_invoker = ON), so the table policies above still apply
// to the caller. These grants only make the views reachable through PostgREST.
const viewGrants = views
  .map(
    (v) => `
GRANT SELECT ON ${v} TO authenticated;
REVOKE ALL ON ${v} FROM anon;`,
  )
  .join('\n');

console.log(
  [
    '-- Generated by scripts/generateTriggersAndPolicies.js',
    helpers,
    triggers,
    tablePolicies,
    viewGrants,
    functionGrants,
  ].join('\n'),
);
