-- Generated by scripts/generateTriggersAndPolicies.js

-- Access level of the current request, from the server-controlled app_metadata claim.
-- search_path is pinned empty (Supabase's DB linter flags mutable search_paths); every
-- reference below is therefore schema-qualified.
-- Falls back to 'readOnly' so a session whose token predates the app_metadata migration
-- degrades to read access rather than being locked out.
CREATE OR REPLACE FUNCTION public.app_access_level()
RETURNS TEXT
LANGUAGE SQL
STABLE
SET search_path = ''
AS $$
  SELECT COALESCE(
    NULLIF(auth.jwt() -> 'app_metadata' ->> 'access_level', ''),
    'readOnly'
  );
$$;

CREATE OR REPLACE FUNCTION public.app_can_write()
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SET search_path = ''
AS $$
  SELECT public.app_access_level() IN ('readWrite', 'admin');
$$;

REVOKE ALL ON FUNCTION public.app_access_level() FROM anon, public;
REVOKE ALL ON FUNCTION public.app_can_write() FROM anon, public;
GRANT EXECUTE ON FUNCTION public.app_access_level() TO authenticated;
GRANT EXECUTE ON FUNCTION public.app_can_write() TO authenticated;


DROP TRIGGER IF EXISTS update_parent_modified_at ON parent;
CREATE TRIGGER update_parent_modified_at
BEFORE UPDATE ON parent
FOR EACH ROW
EXECUTE FUNCTION update_modified_at();

DROP TRIGGER IF EXISTS update_deliverer_modified_at ON deliverer;
CREATE TRIGGER update_deliverer_modified_at
BEFORE UPDATE ON deliverer
FOR EACH ROW
EXECUTE FUNCTION update_modified_at();

DROP TRIGGER IF EXISTS update_kid_modified_at ON kid;
CREATE TRIGGER update_kid_modified_at
BEFORE UPDATE ON kid
FOR EACH ROW
EXECUTE FUNCTION update_modified_at();

DROP TRIGGER IF EXISTS update_order_record_modified_at ON order_record;
CREATE TRIGGER update_order_record_modified_at
BEFORE UPDATE ON order_record
FOR EACH ROW
EXECUTE FUNCTION update_modified_at();

ALTER TABLE parent ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS access_for_logged_in_users ON parent;
DROP POLICY IF EXISTS select_for_authenticated ON parent;
DROP POLICY IF EXISTS insert_for_writers ON parent;
DROP POLICY IF EXISTS update_for_writers ON parent;
DROP POLICY IF EXISTS delete_for_writers ON parent;

-- Everyone signed in may read.
CREATE POLICY select_for_authenticated ON parent
FOR SELECT TO authenticated
USING (true);

-- Only readWrite/admin may change anything.
CREATE POLICY insert_for_writers ON parent
FOR INSERT TO authenticated
WITH CHECK (public.app_can_write());

CREATE POLICY update_for_writers ON parent
FOR UPDATE TO authenticated
USING (public.app_can_write())
WITH CHECK (public.app_can_write());

CREATE POLICY delete_for_writers ON parent
FOR DELETE TO authenticated
USING (public.app_can_write());

REVOKE ALL ON TABLE parent FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE parent TO authenticated;

ALTER TABLE deliverer ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS access_for_logged_in_users ON deliverer;
DROP POLICY IF EXISTS select_for_authenticated ON deliverer;
DROP POLICY IF EXISTS insert_for_writers ON deliverer;
DROP POLICY IF EXISTS update_for_writers ON deliverer;
DROP POLICY IF EXISTS delete_for_writers ON deliverer;

-- Everyone signed in may read.
CREATE POLICY select_for_authenticated ON deliverer
FOR SELECT TO authenticated
USING (true);

-- Only readWrite/admin may change anything.
CREATE POLICY insert_for_writers ON deliverer
FOR INSERT TO authenticated
WITH CHECK (public.app_can_write());

CREATE POLICY update_for_writers ON deliverer
FOR UPDATE TO authenticated
USING (public.app_can_write())
WITH CHECK (public.app_can_write());

CREATE POLICY delete_for_writers ON deliverer
FOR DELETE TO authenticated
USING (public.app_can_write());

REVOKE ALL ON TABLE deliverer FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE deliverer TO authenticated;

ALTER TABLE kid ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS access_for_logged_in_users ON kid;
DROP POLICY IF EXISTS select_for_authenticated ON kid;
DROP POLICY IF EXISTS insert_for_writers ON kid;
DROP POLICY IF EXISTS update_for_writers ON kid;
DROP POLICY IF EXISTS delete_for_writers ON kid;

-- Everyone signed in may read.
CREATE POLICY select_for_authenticated ON kid
FOR SELECT TO authenticated
USING (true);

-- Only readWrite/admin may change anything.
CREATE POLICY insert_for_writers ON kid
FOR INSERT TO authenticated
WITH CHECK (public.app_can_write());

CREATE POLICY update_for_writers ON kid
FOR UPDATE TO authenticated
USING (public.app_can_write())
WITH CHECK (public.app_can_write());

CREATE POLICY delete_for_writers ON kid
FOR DELETE TO authenticated
USING (public.app_can_write());

REVOKE ALL ON TABLE kid FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE kid TO authenticated;

ALTER TABLE order_record ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS access_for_logged_in_users ON order_record;
DROP POLICY IF EXISTS select_for_authenticated ON order_record;
DROP POLICY IF EXISTS insert_for_writers ON order_record;
DROP POLICY IF EXISTS update_for_writers ON order_record;
DROP POLICY IF EXISTS delete_for_writers ON order_record;

-- Everyone signed in may read.
CREATE POLICY select_for_authenticated ON order_record
FOR SELECT TO authenticated
USING (true);

-- Only readWrite/admin may change anything.
CREATE POLICY insert_for_writers ON order_record
FOR INSERT TO authenticated
WITH CHECK (public.app_can_write());

CREATE POLICY update_for_writers ON order_record
FOR UPDATE TO authenticated
USING (public.app_can_write())
WITH CHECK (public.app_can_write());

CREATE POLICY delete_for_writers ON order_record
FOR DELETE TO authenticated
USING (public.app_can_write());

REVOKE ALL ON TABLE order_record FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE order_record TO authenticated;

ALTER TABLE order_parent ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS access_for_logged_in_users ON order_parent;
DROP POLICY IF EXISTS select_for_authenticated ON order_parent;
DROP POLICY IF EXISTS insert_for_writers ON order_parent;
DROP POLICY IF EXISTS update_for_writers ON order_parent;
DROP POLICY IF EXISTS delete_for_writers ON order_parent;

-- Everyone signed in may read.
CREATE POLICY select_for_authenticated ON order_parent
FOR SELECT TO authenticated
USING (true);

-- Only readWrite/admin may change anything.
CREATE POLICY insert_for_writers ON order_parent
FOR INSERT TO authenticated
WITH CHECK (public.app_can_write());

CREATE POLICY update_for_writers ON order_parent
FOR UPDATE TO authenticated
USING (public.app_can_write())
WITH CHECK (public.app_can_write());

CREATE POLICY delete_for_writers ON order_parent
FOR DELETE TO authenticated
USING (public.app_can_write());

REVOKE ALL ON TABLE order_parent FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE order_parent TO authenticated;

ALTER TABLE order_kid ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS access_for_logged_in_users ON order_kid;
DROP POLICY IF EXISTS select_for_authenticated ON order_kid;
DROP POLICY IF EXISTS insert_for_writers ON order_kid;
DROP POLICY IF EXISTS update_for_writers ON order_kid;
DROP POLICY IF EXISTS delete_for_writers ON order_kid;

-- Everyone signed in may read.
CREATE POLICY select_for_authenticated ON order_kid
FOR SELECT TO authenticated
USING (true);

-- Only readWrite/admin may change anything.
CREATE POLICY insert_for_writers ON order_kid
FOR INSERT TO authenticated
WITH CHECK (public.app_can_write());

CREATE POLICY update_for_writers ON order_kid
FOR UPDATE TO authenticated
USING (public.app_can_write())
WITH CHECK (public.app_can_write());

CREATE POLICY delete_for_writers ON order_kid
FOR DELETE TO authenticated
USING (public.app_can_write());

REVOKE ALL ON TABLE order_kid FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE order_kid TO authenticated;

GRANT SELECT ON parent_view TO authenticated;
REVOKE ALL ON parent_view FROM anon;

GRANT SELECT ON finished_order_view TO authenticated;
REVOKE ALL ON finished_order_view FROM anon;

GRANT SELECT ON kid_view TO authenticated;
REVOKE ALL ON kid_view FROM anon;

GRANT SELECT ON parent_options TO authenticated;
REVOKE ALL ON parent_options FROM anon;

GRANT SELECT ON deliverer_options TO authenticated;
REVOKE ALL ON deliverer_options FROM anon;

GRANT SELECT ON kid_order_view TO authenticated;
REVOKE ALL ON kid_order_view FROM anon;

GRANT SELECT ON parent_order_view TO authenticated;
REVOKE ALL ON parent_order_view FROM anon;
