-- The dashboard's "Active Kids" tile counted the `kid` table directly, filtered only on the
-- kid's own `is_active` / `is_deleted`. A kid row says nothing about whether the family is
-- still on the roster, so the number disagreed with both of the places that matter:
--
--   * the Kids list, because `kid_view` drops kids whose parent is soft-deleted; and
--   * the monthly order, because `finishOrder` only snapshots ACTIVE parents.
--
-- So deactivating or deleting a family left its children counted as active on the front
-- page while nobody was ordering diapers for them. Same class of bug as ISSUES #8.
--
-- This view is the countable roster: kid rows whose parent is live and active. It selects
-- the kid's own columns, so the caller's `is_active` / `is_deleted` filters still mean what
-- they meant against the table.

DROP VIEW IF EXISTS rostered_kid_view;
CREATE VIEW rostered_kid_view WITH (security_invoker = ON) AS
SELECT k.*
FROM kid k
JOIN parent p
  ON p.id = k.parent_id
WHERE NOT p.is_deleted
  AND p.is_active;

-- security_invoker, so the RLS policies on `kid` and `parent` still gate the rows. This
-- grant only makes the view reachable through PostgREST — same as every other view, and
-- generated by scripts/generateTriggersAndPolicies.js.
GRANT SELECT ON rostered_kid_view TO authenticated;
